spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  file:
    name: application.log